version: '3'
services:
  back:
    build: ../jalas
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  frontend:
    build: ../jalas-front
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - back
