version: '3'
services:
  back:
    build: ./jalas
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  frontend:
    build: ./jalas-front
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - back
